# render.yaml
# Développé par OceanTechnologie
# Configuration de déploiement pour Render.com

services:

  # Application Laravel (Backend + Frontend)
  - type: web
    name: stocky-app
    env: docker
    dockerfilePath: ./Dockerfile.web
    plan: free
    envVars:
      - key: APP_NAME
        value: "Stocky POS"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://stocky-app.onrender.com
      
      # Base de données (Aiven MySQL)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: stockydb-nestorcorneille-3ea7.i.aivencloud.com
      - key: DB_PORT
        value: 16730
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false # Render vous demandera le mot de passe dans le Dashboard
      - key: MYSQL_ATTR_SSL_CA
        value: "" # Active le SSL implicite requis par Aiven

      # PWA & WebPush
      - key: VAPID_PUBLIC_KEY
        generateValue: true
      - key: VAPID_PRIVATE_KEY
        generateValue: true
      - key: VAPID_SUBJECT
        value: "mailto:contact@oceantechnologie.com"
